name: elephant
adopt-info: elephant
summary: Code editing. Redefined.
description: |
  Binary releases of Code without branding/telemetry/licensing

base: core18
grade: stable
confinement: classic
compression: lzo

parts:
  elephant:
    plugin: nil
    override-build: |
      set -eu
      ARCHITECTURE=$(dpkg --print-architecture)
      # Get GitHub releases
      wget --quiet https://api.github.com/repos/imaegoo/elephant/releases -O latest.json
      VERSION=$(jq -r 'sort_by(.tag_name)|last.tag_name' latest.json)
      DEB_URL=$(jq -r 'map(select(.tag_name == "'"$VERSION"'"))|first.assets[].browser_download_url|select(endswith("'"_$ARCHITECTURE.deb"'"))' latest.json)
      DEB=$(basename "${DEB_URL}")
      # Downloading .deb"
      wget "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Unpacking .deb"
      dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
      rm -f latest.json
      rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      # Set version
      snapcraftctl set-version "$VERSION"
      # Correct path to icon.
      sed -i 's|Icon=elephant|Icon=${SNAP}/usr/share/pixmaps/elephant.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/elephant.desktop
      sed -i 's|Exec=/usr/share/elephant/elephant|Exec=elephant|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/elephant.desktop
      sed -i 's|Icon=elephant|Icon=/usr/share/pixmaps/elephant.png|g' ${SNAPCRAFT_PART_INSTALL}/usr/share/applications/elephant-url-handler.desktop
    build-packages:
      - wget
      - jq
    stage-packages:
      - fcitx-frontend-gtk3
      - gvfs-libs
      - libasound2
      - libgconf-2-4
      - libglib2.0-bin
      - libgnome-keyring0
      - libgtk-3-0
      - libnotify4
      - libnspr4
      - libnss3
      - libpcre3
      - libpulse0
      - libsecret-1-0
      - libxshmfence1
      - libxss1
      - libxtst6
      - zlib1g
      - libx11-xcb1
      - libxkbfile1
      - libdrm2
      - libgbm1
      - libxcb-dri3-0
    prime:
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
      - -usr/share/elephant/chrome-sandbox

  electron-launch:
    after:
      - elephant
    plugin: dump
    source: snap/local

apps:
  elephant:
    command: electron-launch $SNAP/usr/share/elephant/bin/elephant --no-sandbox
    desktop: usr/share/applications/elephant.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas

  url-handler:
    command: electron-launch $SNAP/usr/share/elephant/bin/elephant --open-url --no-sandbox
    desktop: usr/share/applications/elephant-url-handler.desktop
    environment:
      GSETTINGS_SCHEMA_DIR: $SNAP/usr/share/glib-2.0/schemas
